# default:
#   image: docker:24.0.5
#   services:
#     - docker:24.0.5-dind
#   before_script:
#     - docker info
image: docker:24.0.5
services:
  - docker:24.0.5-dind

variables:
  # When you use the dind service, you must instruct Docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket. Docker 19.03 does this automatically
  # by setting the DOCKER_HOST in
  # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03/docker-entrypoint.sh#L23-L29
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/services/#accessing-the-services.
  #
  # Specify to Docker where to create the certificates. Docker
  # creates them automatically on boot, and creates
  # `/certs/client` to share between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - deploy

build-dev:
  stage: build
  tags:
    - build 
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  script:
    - apk add curl
    - | 
      curl --request PUT --header "PRIVATE-TOKEN: $GIT_ACCESS_TOKEN" \
      "https://gitlab.com/api/v4/groups/77764517/variables/LAST_BACKEND_DEVIMAGE_TAG" --form "value=$CI_COMMIT_SHORT_SHA"
    - docker login -u $gitUserName -p $gitPassword registry.gitlab.com
    - docker build -t registry.gitlab.com/artcogen/backend:$CI_COMMIT_SHORT_SHA .
    - docker push registry.gitlab.com/artcogen/backend:$CI_COMMIT_SHORT_SHA


build-prod:
  stage: build
  tags:
    - build 
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - docker login -u $gitUserName -p $gitPassword registry.gitlab.com
    - docker build -t registry.gitlab.com/artcogen/backend:latest .
    - docker push registry.gitlab.com/artcogen/backend:latest

deploy-prod:
  stage: deploy
  tags:
    - deploy
    - shell
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
  script:
    - docker ps -q --filter ancestor=registry.gitlab.com/artcogen/backend:$LAST_BACKEND_DEVIMAGE_TAG | xargs -r docker stop 
    - docker ps -q --filter ancestor=registry.gitlab.com/artcogen/backend:latest | xargs -r docker stop
    - docker system prune -af 
    - docker login -u $gitUserName -p $gitPassword registry.gitlab.com
    - docker pull registry.gitlab.com/artcogen/backend:latest
    - docker run -d -p 127.0.0.1:3001:3001 registry.gitlab.com/artcogen/backend:latest